/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_MoteurC */

#ifndef _Included_jni_MoteurC
#define _Included_jni_MoteurC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_MoteurC
 * Method:    initC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_MoteurC_initC
  (JNIEnv *, jclass);

/*
 * Class:     jni_MoteurC
 * Method:    indexerTexteC
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_jni_MoteurC_indexerTexteC
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     jni_MoteurC
 * Method:    indexerImageC
 * Signature: (Ljava/lang/String;IFI)V
 */
JNIEXPORT void JNICALL Java_jni_MoteurC_indexerImageC
  (JNIEnv *, jclass, jstring, jint, jfloat, jint);

/*
 * Class:     jni_MoteurC
 * Method:    indexerAudioC
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_jni_MoteurC_indexerAudioC
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     jni_MoteurC
 * Method:    rechercherTexteC
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_MoteurC_rechercherTexteC
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     jni_MoteurC
 * Method:    rechercherMotsC
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_MoteurC_rechercherMotsC
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     jni_MoteurC
 * Method:    rechercherImageC
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_MoteurC_rechercherImageC
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     jni_MoteurC
 * Method:    rechercherCouleurC
 * Signature: (III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_MoteurC_rechercherCouleurC
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jni_MoteurC
 * Method:    rechercherAudioC
 * Signature: (Ljava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_MoteurC_rechercherAudioC
  (JNIEnv *, jclass, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
