/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moteur_recherche_CMethods */

#ifndef _Included_moteur_recherche_CMethods
#define _Included_moteur_recherche_CMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moteur_recherche_CMethods
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moteur_1recherche_CMethods_init
  (JNIEnv *, jclass);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    indexerTexte
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moteur_1recherche_CMethods_indexerTexte
  (JNIEnv *, jclass);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    indexerImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moteur_1recherche_CMethods_indexerImage
  (JNIEnv *, jclass);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    indexerAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_moteur_1recherche_CMethods_indexerAudio
  (JNIEnv *, jclass);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    rechercherTexte
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moteur_1recherche_CMethods_rechercherTexte
  (JNIEnv *, jclass, jstring);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    rechercherMots
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moteur_1recherche_CMethods_rechercherMots
  (JNIEnv *, jclass, jstring);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    rechercherImage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moteur_1recherche_CMethods_rechercherImage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    rechercherCouleur
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moteur_1recherche_CMethods_rechercherCouleur
  (JNIEnv *, jclass, jint);

/*
 * Class:     moteur_recherche_CMethods
 * Method:    rechercherAudio
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_moteur_1recherche_CMethods_rechercherAudio
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
